name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: |
        poetry install --with dev
    
    - name: Run Black
      run: |
        poetry run black --check --diff .
    
    - name: Run isort
      run: |
        poetry run isort --check-only --diff .
    
    - name: Run flake8
      run: |
        poetry run flake8 .
    
    - name: Run mypy
      run: |
        poetry run mypy .
    
    - name: Run codespell
      run: |
        poetry run codespell