name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort pylint mypy codespell
    
    - name: Run Black
      run: |
        black --check --diff .
    
    - name: Run isort
      run: |
        isort --check-only --diff .
    
    - name: Run flake8
      run: |
        flake8 --max-line-length=88 --extend-ignore=E203,W503 --exclude=.venv,venv,.git,__pycache__,*.egg-info,build,dist .
    
    - name: Run pylint
      run: |
        pylint **/*.py
    
    - name: Run mypy
      run: |
        mypy .
    
    - name: Run codespell
      run: |
        codespell